import { Product } from "./types/product";

export const PRODUCTS: Product[] = [
  {
    id: 1,
    title: "Vanilla Ice Cream",
    slug: "vanilla-ice-cream",
    heroImage: require("../assets/images/coffee-1.jpg"),
    imagesUrl: [require("../assets/images/coffee-1.jpg"), require("../assets/images/coffee-2.jpg"), require("../assets/images/coffee-3.jpg"), require("../assets/images/coffee-4.jpg")],
    price: 25.0,
    category: {
      imageUrl: require("../assets/images/coffee-1.jpg"),
      name: "Coffee",
      slug: "coffee",
    },
    maxQuantity: 5,
  },
  {
    id: 5,
    title: "Donut with Caramel",
    slug: "donut-with-caramel",
    heroImage: require("../assets/images/dessert-1.jpg"),
    imagesUrl: [require("../assets/images/dessert-1.jpg"), require("../assets/images/dessert-2.jpg"), require("../assets/images/dessert-3.jpg"), require("../assets/images/dessert-4.jpg")],
    price: 15.0,
    category: {
      imageUrl: require("../assets/images/dessert-1.jpg"),
      name: "Desserts",
      slug: "desserts",
    },
    maxQuantity: 7,
  },
  {
    id: 2,
    title: "Tea with Lemon",
    slug: "tea-with-lemon",
    heroImage: require("../assets/images/tea-1.jpg"),
    imagesUrl: [require("../assets/images/tea-2.jpg"), require("../assets/images/tea-3.jpg")],
    price: 10.0,
    category: {
      imageUrl: require("../assets/images/tea-1.jpg"),
      name: "Tea",
      slug: "tea",
    },
    maxQuantity: 10,
  },
  {
    id: 6,
    title: "Chocolate Cake",
    slug: "chocolate-cake",
    heroImage: require("../assets/images/food-1.jpg"),
    imagesUrl: [require("../assets/images/food-1.jpg"), require("../assets/images/food-2.jpg"), require("../assets/images/food-3.jpg"), require("../assets/images/food-4.jpg")],
    price: 25.0,
    category: {
      imageUrl: require("../assets/images/food-1.jpg"),
      name: "Foods",
      slug: "foods",
    },
    maxQuantity: 12,
  },
  {
    id: 3,
    title: "Pack of Cookies",
    slug: "pack-of-cookies",
    heroImage: require("../assets/images/pack-1.jpg"),
    imagesUrl: [require("../assets/images/pack-1.jpg"), require("../assets/images/pack-2.jpg")],
    price: 30.0,
    category: {
      imageUrl: require("../assets/images/pack-1.jpg"),
      name: "Packages",
      slug: "packages",
    },
    maxQuantity: 15,
  },
  {
    id: 4,
    title: "dark chocolate",
    slug: "dark-chocolate",
    heroImage: require("../assets/images/coffee-4.jpg"),
    imagesUrl: [require("../assets/images/coffee-4.jpg"), require("../assets/images/coffee-2.jpg"), require("../assets/images/coffee-3.jpg")],
    price: 26.0,
    category: {
      imageUrl: require("../assets/images/coffee-1.jpg"),
      name: "Coffee",
      slug: "coffee",
    },
    maxQuantity: 3,
  },
  // {
  //   id: 7,
  //   title: 'Nintendo Switch',
  //   slug: 'nintendo-switch',
  //   heroImage: require('../assets/images/nintendo-switch-1.jpg'),
  //   imagesUrl: [
  //     require('../assets/images/nintendo-switch-1.jpg'),
  //     require('../assets/images/nintendo-switch-2.jpg'),
  //   ],
  //   price: 299.99,
  //   category: {
  //     imageUrl: require('../assets/images/ps-5-1.jpg'),
  //     name: 'Gaming',
  //     slug: 'gaming',
  //   },
  //   maxQuantity: 8,
  // },
];
